### PR TITLE
Make buttons to be like  Webmaker style down/hover states

### LINKED ISSUE #152: Buttons need Webmaker style down/hover states
Buttons on all pages need to match the Webmaker style for down and hover states (can be seen on teach.mofostaging.net).

### PR DESCRIPTION
**Pull request by alicoding**
fixes #152

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron R?

**Comment by secretrobotron** [comment]
R+

The `/reset-password` button looks pretty wonky though. Wanna fix that here, or separate issue?

screenshot 2015-04-08 07 10 05

**Comment by secretrobotron** [comment]
Actually, have a look at the colour of all the buttons. In their default state, they're a totally different shade of green than the design.

**Comment by alicoding** [comment]
@secretrobotron fixed! :D

**Comment by secretrobotron** [comment]
Measured by **Digital Color Meter**:
Old colour: `88  191 163`
New colour: `32  183 133`

Looks like there's a thin white keyline (or shadow or something) on the top of the buttons too now. On purpose?

**Pull request merged**
