### PR TITLE
set credentials mode to 'same-origin' when using fetch API

### PR DESCRIPTION
**Pull request by cadecairos**

### CODE REVIEW

**Comment by cadecairos** [comment]
@alicoding R?

**Comment by secretrobotron** [comment]
Does the `/request-migration-email` fetch in `migrate.jsx` need one too?

**Comment by alicoding** [comment]
Code looking good r+ with what @secretrobotron mention too

**Comment by cadecairos** [comment]
> Does the /request-migration-email fetch in migrate.jsx need one too?

The commit adds a credentials flag there already?

**Comment by alicoding** [comment]
Ah! True.

**Comment by secretrobotron** [comment]
Haha nope. It's not there. Heads up @alicoding.

**Pull request merged**
