### PR TITLE
'Forgot password' link needs to be vertically aligned #154

### LINKED ISSUE #154: "Forgot password" link needs to be vertically aligned
The "Forgot password" link on the login page needs to be aligned with the baseline of the button next to it.

### PR DESCRIPTION
**Pull request by alicoding**
fixes #154

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron r?

**Comment by secretrobotron** [comment]
Should probably be `53px` or `54px`. Tools used to verify: a ruler :P.

**Comment by alicoding** [comment]
54 looking good @secretrobotron

**Comment by secretrobotron** [comment]
ship it

**Pull request merged**
