### PR TITLE
Manual tests

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by alicoding** [comment]
hmm do we want to commit these two files?

` public/manual.bundle.js` and ` public/manual.bundle.js.map`?

**Comment by alicoding** [comment]
r+ with removing that two files and add them as part of `.gitignore`?

**Comment by k88hudson** [comment]
oh right! good catch

**Comment by k88hudson** [comment]
@alicoding what do you think about ignoring `*.bundle.*`

**Comment by alicoding** [comment]
I like that approach good thinking! r+!

**Pull request merged**
