### PR TITLE
 Textbox icons are not vertically aligned #150

### LINKED ISSUE #150: Textbox icons are not vertically aligned
The icons in textboxes on `/login` (etc.) are not vertically aligned. Should be `19px`.

### PR DESCRIPTION
**Pull request by alicoding**
fixes #150

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron r?

**Comment by secretrobotron** [comment]
R+
But, think the text should be bumped down a pixel or two now too?

**Comment by alicoding** [comment]
Done @secretrobotron R?

**Comment by secretrobotron** [comment]
Hmm. Looks fine on Firefox, but too low on Chrome now:
screenshot 2015-04-08 11 36 39

**Comment by alicoding** [comment]
@secretrobotron this should now be fixed!

**Comment by secretrobotron** [comment]
@alicoding fix the warning icons too?
screenshot 2015-04-08 13 19 53

**Comment by alicoding** [comment]
@secretrobotron done \o/

**Comment by secretrobotron** [comment]
SHIP IT

**Pull request merged**
