### PR TITLE
Fix #148 error message tooltip alignment is off

### LINKED ISSUE #148: Signup page: error message tooltip alignment is off
Signup page error messages should be `right: 10px` to have them line up with the warning icon inside the textbox.

(should be on the `.warning` element)

### PR DESCRIPTION
**Pull request by alicoding**
closes #148

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron R?

This should be pretty dynamic now :D

**Comment by secretrobotron** [comment]
Still looks a *bit* off (should be over to the right a couple more pixels, I think).

screenshot 2015-04-08 06 57 30
screenshot 2015-04-08 06 58 14

**Comment by alicoding** [comment]
r?

**Comment by secretrobotron** [comment]
SHIP!

**Pull request merged**
