### PR TITLE
fix #107 - form design QA fixes

### LINKED ISSUE #107: Match form labels and padding on login and signup
Noticed there are some style inconsistencies between the two forms on Signup and Login. The forms should be for the most part the same – specifically they should share:
* the same text size for field labels
* the same padding around the edges of the form (which should be 30px; currently on login the padding is too small and on signup the padding is too big)
* the same vertical space between fields (should be 10px)

match-login-signup-forms

### PR DESCRIPTION
**Pull request by alicoding**
fixes #107

### CODE REVIEW

**Comment by alicoding** [comment]
@secretrobotron R?

**Comment by secretrobotron** [comment]
I'm actually not seeing that `/login` and `/signup` have the same spacing. `/login` looks much thinner between form boxes.

The padding on the bottom of the `/login` box looks a bit fat too.

@alicoding seeing the same?

**Comment by alicoding** [comment]
This is what I see @secretrobotron 

-243ctay
1lys2j9d
2zhluxzh
e11otu18
jp2akw5p
mlulwqs6
rd61imfm
v8eglij_

**Comment by alicoding** [comment]
45b9ess1
zjybeis2

**Comment by secretrobotron** [comment]
`/reset-password` looks like it might need a touch-up as well. @alicoding ?

**Comment by alicoding** [comment]
@secretrobotron done :) I've also fixed up for `/migrate` as well :)

**Comment by secretrobotron** [comment]
did you mean to add the changes for `migrate.jsx`? https://github.com/mozilla/id.webmaker.org/pull/124/files#diff-f6d57c42a67fcde837f5a669bfc6f24c

**Comment by alicoding** [comment]
Yes! Sorry forgot to mention that it was set to true for last step which is
weird so I've changed it to start from the first step.

**Comment by secretrobotron** [comment]
r+

**Pull request merged**
