### PR TITLE
fixed migrate flow copy as per t13

### LINKED ISSUE #13: Copy QA review

### PR DESCRIPTION
**Pull request by secretrobotron**
fixes #13

### CODE REVIEW

**Comment by secretrobotron** [comment]
@alicoding r?

**Comment by secretrobotron** [comment]
@edrushka look better?

screenshot 2015-04-20 13 32 46

screenshot 2015-04-20 13 33 32

**Comment by alicoding** [comment]
looks good to me! r+

**Comment by edrushka** [comment]
If you do another round of changes I might simplify even further to:
"Uh oh. There isn't a password for that account yet."

**Comment by secretrobotron** [comment]
@edrushka done

**Pull request merged**
