### PR TITLE
Use a pre-eslint version of mofo-style

### PR DESCRIPTION
**Pull request by cadecairos**
ESLinting provided by the latest mofo-style breaks us. setting a hard dependency on v1.1.0

### CODE REVIEW

**Comment by alicoding** [comment]
r+

**Comment by alicoding** [comment]
travis is failing.

**Comment by cadecairos** [comment]
Yeah I can't get it to fail locally though. looks like a problem with phantomjs and travis

**Comment by alicoding** [comment]
merge it if you think this is travis only

**Pull request merged**
