### PR TITLE
Fix issue #317 - Change from username to email for password recovery …

### LINKED ISSUE #317: Can't recover password if I forgot my username
Lost password form requires a username. Can we set this to accept either username or email for ID? If not, email might be the better option since recovery will happen using it. It must be known.

### PR DESCRIPTION
**Pull request by alicoding**
Closes #317 

In this patch I've changed from username to email to recovery password, and I also remove query that we are passing from login page since that could be a username which we are no longer allowed on password recovery page.

### CODE REVIEW

**Comment by alicoding** [comment]
@cadecairos r?

**Comment by cadecairos** [comment]
r- 

This reset form should allow for username or email

**Comment by alicoding** [comment]
@cadecairos https://github.com/mozilla/id.webmaker.org/issues/317#issuecomment-119323340

**Comment by cadecairos** [comment]
R+

**Comment by xmatthewx** [comment]
Hitting some validation bugs on staging. 

STR: 
 - enter an email address that isn't in the db
  - results: a good failure message
 - enter another email address
  - results: incorrect validation message
 - enter a new string without `@`
  - results: incorrect username error
 - enter another email address
 - unable to submit

screenshot 2015-07-08 13 03 37
screenshot 2015-07-08 13 04 35

**Comment by xmatthewx** [comment]
tested via https://id.mofostaging.net/reset-password/

**Pull request merged**
