### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by kritisingh1**
favicon is added to the signup page of id.webmaker.org. PR #442 . Let me know if any changes are required. This is in reference to the issue opened by @flukeout  as #434

### CODE REVIEW

**Comment by flukeout** [comment]
Cool, thanks for submitting! A few comments...

Can use the favicon that is currently being used on the [mozilla website](https://www.mozilla.org/en-US/)

* Image is here - https://www.mozilla.org/media/img/favicon/favicon-196x196.png

Also, let's remove the changes to the ``package.json`` file. We are including the icon explicitly in the pages anyway, so I don't think we need to rely on that. Thanks!

**Comment by kritisingh1** [comment]
@flukeout I have made the suggested changes and pushed to the fork. Thanks a lot.

**Comment by kritisingh1** [comment]
@flukeout I have made the required the changes. Can you please review and
merge my PR now? Thanks a lot.

**Comment by flukeout** [comment]
Hi @kritisingh1 - testing locally now, thanks!

**Comment by flukeout** [comment]
Great work @kritisingh1 - tested locally and the favicon shows up as expected.

**Comment by kritisingh1** [comment]
Thanks @flukeout

**Pull request merged**
