### PR TITLE
Add form validation for all pages

### PR DESCRIPTION
**Pull request by alicoding**
@cadecairos R?

### CODE REVIEW

**Comment by cadecairos** [comment]
you need to fix those travis failures

**Comment by cadecairos** [comment]
invalid password

I don't think this should say invalid password. It should say "Invalid Username or Password"

**Comment by cadecairos** [comment]
noexist

Perhaps we should make this a friendlier error? "Whoops! We can't find an account with that username!"

**Comment by alicoding** [comment]
Test should pass now

**Comment by alicoding** [comment]
@cadecairos r?

**Comment by alicoding** [comment]
no lie but this time tests are fixed for sure @cadecairos :P

**Comment by cadecairos** [comment]
R+

**Pull request merged**
