### PR TITLE
Node 6 update

### PR DESCRIPTION
**Pull request by Pomax**

### CODE REVIEW

**Comment by alanmoo** [comment]
Given that Travis failed, does this repo need update to work with Node 6?

**Comment by cadecairos** [comment]
If i recall correctly this is a bug in eslint that we can fix with a flag.... I think I saw @gideonthomas fix it before somewhere.

**Comment by gideonthomas** [comment]
lol really? uhhhh, maybe it's in a closed pr, let me check.

**Comment by cadecairos** [comment]
> lol really? uhhhh, maybe it's in a closed pr, let me check.

I'm not sure if it was in this repo or not... don't you remember fixing some rando error about leaking somthing-or-other?

**Comment by cadecairos** [comment]
maybe in publish?

**Comment by Pomax** [comment]
@cadecairos @gideonthomas fixed the issue by bumping lab - R?

**Pull request merged**
