### PR TITLE
Pass a more meaningful error from login server

### PR DESCRIPTION
**Pull request by cadecairos**
mozilla/webmaker-android#2216

### CODE REVIEW

**Comment by k88hudson** [comment]
Any we could change he error message from 

```
Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: Users.username
``

to something like `That username is taken`?

**Comment by cadecairos** [comment]
@k88hudson  We can do that here, or in  mozilla/webmaker-android#2216, Where would you prefer?

**Comment by k88hudson** [comment]
@cadecairos I think it would be better to do on id.webmaker.org since error messages might change here/get out of sync in the app etc.

**Comment by cadecairos** [comment]
okay, I'll check for each type of constraint error here.

**Comment by k88hudson** [comment]
Thanks!

**Comment by k88hudson** [comment]
R+ Awesome, thanks so much for doing this!

**Pull request merged**
